### ISSUE TITLE
Yosemite "Please install mpg123 headers" using macports

### ISSUE THREAD

**Issue by yebo29** [grobie/soundcloud2000#76]
I know I am straying off the instructions but wanted to give it a shot anyways. Following the instructions but using macports instead (sudo port install mpg123), gem install bombs out stating it is unable to find the mpg123 headers. Namely, mpg123.h. I made a search and found the library in /opt/local/include/mpg123.h. I then ran "sudo gem install soundcloud2000 -- --with-opt-lib=/opt/local/include/" with the same unsuccessful result:

sudo gem install soundcloud2000 -- --with-opt-lib=/opt/local/include/
Building native extensions with: '--with-opt-lib=/opt/local/include/'
This could take a while...
ERROR:  Error installing soundcloud2000:
    ERROR: Failed to build gem native extension.

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb --with-opt-lib=/opt/local/include/
```

checking for mpg123.h... no
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
please install mpg123 headers

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/audite-0.4.0 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/audite-0.4.0/ext/mpg123/gem_make.out
MBP15LMG3QD:~ dsanpedro$ port search mpg123
mpg123 @1.21.0 (audio)
    fast mp3 player for linux and unix systems

mpg321 @0.2.10_3 (audio)
    Free replacement for mpg123

Found 2 ports

Thanks!

**Comment by tomdeboer** [comment]
Can you try this: ```sudo gem install soundcloud2000 -- --with-opt-include=/usr/local/include``` ?

**Comment by yebo29** [comment]
No dice :(

$ sudo gem install soundcloud2000 -- --with-opt-include=/usr/local/include
Password:
Building native extensions with: '--with-opt-include=/usr/local/include'
This could take a while...
ERROR:  Error installing soundcloud2000:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb --with-opt-include=/usr/local/include
checking for mpg123.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
please install mpg123 headers


Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/audite-0.4.0 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/audite-0.4.0/ext/mpg123/gem_make.out

**Comment by tomdeboer** [comment]
I use brew instead of Macports, but have you done the obligatory (I'm guessing) ```sudo ports mpg123 portaudio```

**Comment by yebo29** [comment]
Yes, I have.

**Comment by yebo29** [comment]
Wondering what brew does so differently from macports?

**Comment by yebo29** [comment]
Is there a way to manually override the location the installer looks for besides using the  --with-opt-include switch?
