### ISSUE TITLE
Update the soundcloud2000 ruby gem

### ISSUE THREAD

**Issue by SophisticaSean** [grobie/soundcloud2000#80]
The current ruby gem is still running a fairly old build. That old build still has a ton of crashing problems. Need to get permissions from grobie to update the gem.

**Comment by grobie** [comment]
I need your rubygems.org email address for that. The same you use when committing?

**Comment by SophisticaSean** [comment]
Yes sir, sensaisean@gmail.com, handle is sophisticasean

**Comment by grobie** [comment]
Have fun: https://rubygems.org/gems/soundcloud2000
