### ISSUE TITLE
Not really an issue with the software, but I dont think we can get soundcloud client ids anymore :(

### ISSUE THREAD

**Issue by craftfortress** [grobie/soundcloud2000#97]
Has anyone got a solution?

The link is also not working in the readme for the soundcloud client credential get

Its a shame I was looking forward to use this

**Comment by qysp** [comment]
For anyone who doesn't know how to obtain the client ID:
* open developer console & go to the "Network" tab
* log into your SoundCloud account and look for a call to `api.soundcloud.com`
* look at the full request url and extract the `client_id` query parameter value

**Comment by craftfortress** [comment]
Thank you and god speed
